import os
import io
import contextlib
import streamlit as st
from autogen import AssistantAgent, UserProxyAgent
from google import genai
from google.genai import types
from io import BytesIO
from docx import Document
import csv
from fpdf import FPDF
from dotenv import load_dotenv

# Load GEMINI_API_KEY from .env
load_dotenv()

st.set_page_config(page_title="Gemini Research Agent", layout="centered")

# AutoGen needs the key in this format
config_list_gemini = [
    {"model": "gemini-2.5-flash", "api_key": os.getenv("GEMINI_API_KEY"), "api_type": "google"}
]

# google-genai client — used separately for streaming the full answer
gemini_client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
MODEL = "gemini-2.5-flash"
SYSTEM = "You are a helpful research assistant. Provide thorough, well-structured responses."


# --- Session state ---
# Streamlit reruns the entire script on every interaction, so we persist
# state across reruns using st.session_state
for key, default in {
    "messages": [],        # full conversation history shown in the chat UI
    "outline": None,       # the plan generated by AutoGen, waiting for human approval
    "pending_input": None, # the user's question held until they approve the plan
    "assistant": None,     # AutoGen AssistantAgent (kept alive across reruns)
    "user_proxy": None,    # AutoGen UserProxyAgent (kept alive across reruns)
}.items():
    if key not in st.session_state:
        st.session_state[key] = default


# --- Agent setup ---

def init_agents():
    # AssistantAgent: backed by Gemini, generates the plan and handles redirects
    assistant = AssistantAgent(
        name="assistant",
        llm_config={"config_list": config_list_gemini, "seed": 42},
        system_message=SYSTEM,
    )
    # UserProxyAgent: relays the prompt and collects the reply
    # human_input_mode="NEVER" — Streamlit handles the human turn, not the terminal
    # max_consecutive_auto_reply=0 — stop after one round trip, don't loop
    user_proxy = UserProxyAgent(
        name="user_proxy",
        code_execution_config=False,
        human_input_mode="NEVER",
        max_consecutive_auto_reply=0,
    )
    return assistant, user_proxy


def get_autogen_reply(prompt: str) -> str:
    # Create agents on first use; reuse them on subsequent calls so
    # AutoGen retains the conversation history between turns
    if st.session_state.assistant is None:
        st.session_state.assistant, st.session_state.user_proxy = init_agents()

    assistant = st.session_state.assistant
    user_proxy = st.session_state.user_proxy

    # redirect_stdout/stderr silences AutoGen's "TERMINATING RUN" print output
    with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
        user_proxy.initiate_chat(
            assistant,
            message=prompt,
            clear_history=False,  # keep previous turns as context
            silent=True,
        )

    # Read the last assistant message from AutoGen's internal history
    history = assistant.chat_messages.get(user_proxy, [])
    for msg in reversed(history):
        if isinstance(msg, dict) and msg.get("role") == "assistant":
            return msg.get("content", "").strip()
    return ""


# --- Streaming helpers (google-genai) ---

def to_gemini_contents(extra: str | None = None) -> list:
    # Build a Gemini-compatible content list from our stored message history
    # so the model always has full conversation context
    contents = []
    for m in st.session_state.messages:
        role = "user" if m["role"] == "user" else "model"  # Gemini uses "model" not "assistant"
        contents.append(types.Content(role=role, parts=[types.Part(text=m["content"])]))
    if extra:
        # Append the new user turn (not yet saved to messages)
        contents.append(types.Content(role="user", parts=[types.Part(text=extra)]))
    return contents


def stream_answer(user_input: str, outline: str):
    # Stream the full answer token by token after the human approved the plan
    # The approved outline is passed as context so the model follows it
    contents = to_gemini_contents(f"{user_input}\n\n[Approved plan: {outline}]")
    for chunk in gemini_client.models.generate_content_stream(
        model=MODEL,
        contents=contents,
        config=types.GenerateContentConfig(system_instruction=SYSTEM),
    ):
        if chunk.text:
            yield chunk.text  # st.write_stream consumes these tokens one by one


def stream_direct(prompt: str):
    # Stream a quick action (Generate Subtopics / Summarise) — no plan phase needed
    for chunk in gemini_client.models.generate_content_stream(
        model=MODEL,
        contents=to_gemini_contents(prompt),
        config=types.GenerateContentConfig(system_instruction=SYSTEM),
    ):
        if chunk.text:
            yield chunk.text


def reset_conversation():
    # Wipe everything — messages, plan state, and the AutoGen agents
    st.session_state.messages = []
    st.session_state.outline = None
    st.session_state.pending_input = None
    st.session_state.assistant = None
    st.session_state.user_proxy = None


# --- UI ---
st.title("Gemini Research Agent")

# Top action buttons — disabled until there is at least one message in history
has_messages = bool(st.session_state.messages)
col1, col2, col3 = st.columns(3)

with col1:
    # Bypass the plan phase and directly stream a subtopics breakdown
    if st.button("Generate Subtopics", use_container_width=True, disabled=not has_messages):
        prompt = "Based on our conversation, generate a list of subtopics in bullet points."
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("assistant"):
            response = st.write_stream(stream_direct(prompt))
        st.session_state.messages.append({"role": "assistant", "content": response})
        st.rerun()

with col2:
    # Bypass the plan phase and directly stream a summary
    if st.button("Summarise", use_container_width=True, disabled=not has_messages):
        prompt = "Please summarise our conversation so far concisely."
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("assistant"):
            response = st.write_stream(stream_direct(prompt))
        st.session_state.messages.append({"role": "assistant", "content": response})
        st.rerun()

with col3:
    if st.button("Reset", use_container_width=True, type="secondary"):
        reset_conversation()
        st.rerun()

st.divider()

# Replay the full conversation history in the chat UI
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])


# --- HITL gate ---
# st.session_state.outline acts as a gate:
#   - set   → show the plan and wait for human decision (Phase 2)
#   - None  → show the chat input and wait for a new question (Phase 1)

# Phase 2: an outline is waiting for human approval
if st.session_state.outline:
    with st.chat_message("assistant"):
        st.markdown("**Here's my plan before I answer:**")
        st.markdown(st.session_state.outline)

    st.info("Approve the plan or redirect me.")
    proceed_col, redirect_col = st.columns([1, 2])

    with proceed_col:
        # Human is happy with the plan → stream the full answer
        if st.button("Proceed", type="primary", use_container_width=True):
            user_input = st.session_state.pending_input
            outline = st.session_state.outline
            # Clear the gate before streaming so the UI doesn't get stuck
            st.session_state.outline = None
            st.session_state.pending_input = None
            # Save the original question to history
            st.session_state.messages.append({"role": "user", "content": user_input})
            with st.chat_message("assistant"):
                # st.write_stream renders tokens as they arrive
                full_response = st.write_stream(stream_answer(user_input, outline))
            st.session_state.messages.append({"role": "assistant", "content": full_response})
            st.rerun()

    with redirect_col:
        # Human wants a different direction → ask AutoGen to revise the plan
        with st.form("redirect_form"):
            feedback = st.text_input(
                "Redirect:", placeholder="e.g. focus more on X, avoid Y, be more concise..."
            )
            if st.form_submit_button("Update Plan", use_container_width=True):
                if feedback.strip():
                    redirect_prompt = (
                        f"The user asked: {st.session_state.pending_input}\n\n"
                        f"Your previous outline was rejected. Feedback: {feedback}\n\n"
                        "Provide a revised 2-3 bullet point outline. Plan only, not the full answer."
                    )
                    with st.spinner("Revising plan..."):
                        new_outline = get_autogen_reply(redirect_prompt)
                    # Replace the old outline — human will see the revised plan on next render
                    st.session_state.outline = new_outline
                    st.rerun()

# Phase 1: no outline pending — accept the next user question
else:
    if user_input := st.chat_input("Ask a question or continue the conversation..."):
        outline_prompt = (
            f"The user asked: {user_input}\n\n"
            "Briefly outline in 2-3 bullet points how you will approach answering this. "
            "Plan only — not the full answer yet."
        )
        with st.spinner("Planning..."):
            # AutoGen generates the short plan; stored in session state to show to the human
            outline = get_autogen_reply(outline_prompt)
        st.session_state.outline = outline
        st.session_state.pending_input = user_input
        # Rerun so the HITL gate above renders the plan and Proceed/Redirect options
        st.rerun()


# --- Downloads (visible once there is conversation history) ---
if st.session_state.messages:
    st.divider()
    st.markdown("### Download Conversation")
    dl1, dl2, dl3 = st.columns(3)

    with dl1:
        # Build a Word doc with each message as a labelled paragraph
        doc = Document()
        for m in st.session_state.messages:
            doc.add_heading("You" if m["role"] == "user" else "Assistant", level=2)
            doc.add_paragraph(m["content"])
        word_io = BytesIO()
        doc.save(word_io)
        word_io.seek(0)
        st.download_button(
            "Download Word", data=word_io, file_name="conversation.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            use_container_width=True,
        )

    with dl2:
        # Build a CSV with Role and Content columns
        csv_str_io = io.StringIO()
        writer = csv.writer(csv_str_io)
        writer.writerow(["Role", "Content"])
        for m in st.session_state.messages:
            writer.writerow([m["role"], m["content"]])
        st.download_button(
            "Download CSV", data=BytesIO(csv_str_io.getvalue().encode("utf-8")),
            file_name="conversation.csv", mime="text/csv", use_container_width=True,
        )

    with dl3:
        # Build a PDF; encode to latin-1 to avoid fpdf character errors
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        for m in st.session_state.messages:
            pdf.set_font("Arial", "B", 12)
            pdf.cell(0, 10, "You:" if m["role"] == "user" else "Assistant:", ln=True)
            pdf.set_font("Arial", size=11)
            safe = m["content"].encode("latin-1", errors="replace").decode("latin-1")
            pdf.multi_cell(0, 8, safe)
            pdf.ln(4)
        pdf_bytes = pdf.output(dest="S").encode("latin-1")
        st.download_button(
            "Download PDF", data=BytesIO(pdf_bytes),
            file_name="conversation.pdf", mime="application/pdf",
            use_container_width=True,
        )
